name: Continous integration
on: [push]
env:
  IS_GITHUB: 1
jobs:
  Run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        echo "hello ${{ env.IS_GITHUB }}"
        python src/ExplorerSB/constants.py
        #nosetests tests
